[versions]
java-compile = "21"
java-support = "8"
checkstyle = "10.25.0"
junit = "5.14.0"

[plugins]
shadow = "com.gradleup.shadow:8.3.9"

[libraries]
# lint
rulebook-checkstyle = "com.hanggrian.rulebook:rulebook-checkstyle:0.1"
# main
guava = "com.google.guava:guava:33.5.0-jre"
chalk = "com.github.tomas-langer:chalk:1.0.2"
# test
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = "org.junit.platform:junit-platform-launcher:1.14.0"
mockito-junit-jupiter = "org.mockito:mockito-junit-jupiter:5.20.0"
truth = "com.google.truth:truth:1.4.5"

[bundles]
junit5 = [
  "junit-jupiter",
  "mockito-junit-jupiter",
  "truth",
]
